name: nondito_soft_demo
version: 1.0.0+1
publish_to: none
description: A Flutter project to do work assesment for NonditoSOft.
environment: 
  sdk: ^3.5.3

dependencies: 
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

